version: "2"
services:
  influxdb_svc:
    image: influxdb
    container_name: influxdb_container
    ports:
      - 8083:8083
      - 8086:8086
    restart: always
  telegraf_svc:
    image: telegraf
    container_name: telegraf_container
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
    restart: always
    links:
      - influxdb_svc
    depends_on:
      - influxdb_svc
    volumes:
      - ./persistence/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  grafana_svc:
    image: grafana/grafana
    container_name: grafana_container
    restart: always
    ports:
      - 3003:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    depends_on:
      - influxdb_svc