version: "2"
services:
  influxdb_svc:
    image: influxdb:1.3.5
    container_name: influxdb_container
    ports:
      - 8083:8083
      - 8086:8086
    restart: always
  telegraf_svc:
    image: telegraf:1.4.0
    container_name: telegraf_container
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
    restart: always
    links:
      - influxdb_svc
    depends_on:
      - influxdb_svc
    volumes:
      - ./persistence/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  grafana_svc:
    image: grafana/grafana:5.0.1
    container_name: grafana_container
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
    depends_on:
      - influxdb_svc
  python_alpine:
    image: python:alpine
    container_name: python_alpine_script_runner
    environment:
      GRAFANA_URL: http://grafana_svc:3000
      GRAFANA_USER: admin
      GRAFANA_PASS: admin123
      INFLUXDB_URL: http://localhost:8086
      DATASOURCE_DATA_FILE: datasources.json
      DASHBOARD_DATA_FILES: basic-metrics.json
    volumes:
      - ./persistence/grafana:/tmp
    depends_on:
      - grafana_svc
    links:
      - grafana_svc
    command: python /tmp/init-grafana.py