version: "2"
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - ./persistence/mysql:/var/lib/mysql
    networks:
      - net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7.9-1
    depends_on:
      - "mysql"
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
      - PMA_PORT=3306
    restart: always
    networks:
      - net
  wordpress:
    image: wordpress:4.9.4-php5.6-fpm-alpine
    ports:
      - 8080:80
    volumes:
      - ./persistence/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin123
    depends_on:
      - mysql
    networks:
      - net
networks:
  net:
    driver: bridge

