version: "2"
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.4
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: ches/kafka:0.10.2.1
    ports:
      - "9092:9092"
    depends_on:
      - "zookeeper"
    volumes:
      - ./persistence/data:/data
      - ./persistence/logs:/logs
    environment:
      ZOOKEEPER_IP: zookeeper
      KAFKA_ADVERTISED_HOST_NAME: localhost
    restart: always